web:
  image: server4001/nginx:latest
  ports:
    - "80:80"
  volumes:
    - ./src:/var/www
    - ./src/php-nginx.conf:/etc/nginx/sites-enabled/php-nginx.conf
  links:
    - php
php:
  image: nmcteam/php56:latest
  volumes:
    - ./src/php-fpm.conf:/etc/php5/fpm/php-fpm.conf
    - ./src:/var/www
  links:
    - db
db:
  image: sameersbn/mysql:latest
  volumes:
    - /var/lib/mysql
  environment:
    - DB_NAME=demoDb
    - DB_USER=demoUser
    - DB_PASS=demoPass
