version: '2'

services:

  nginx:
    # docker build -f ./docker/nginx/prod.Dockerfile -t server4001/silex-nginx-prod:0.1.0 .
    image: server4001/silex-nginx-prod:0.1.0
    volumes:
      - ../certs:/etc/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks:
      - silex-network
    mem_limit: 128000000
    container_name: "nginx"

  php:
    # docker build -f ./docker/php/prod.Dockerfile -t server4001/silex-php-prod:0.2.0 .
    image: server4001/silex-php-prod:0.2.0
    working_dir: /application
    env_file: ../.env.prod
    networks:
      - silex-network
    mem_limit: 256000000
    container_name: "php"

  # TODO : Remove. Likely RDS would be used.
  db:
    image: sameersbn/mysql:latest
    volumes:
      - /var/lib/docker-persistant-data/mysql-storage:/var/lib/mysql
    environment:
      - DB_NAME=silex
      - DB_USER=silex_user
      - DB_PASS=silex_password
    networks:
      - silex-network
    mem_limit: 128000000
    container_name: "db"

  # TODO : Remove. Likely Elasticache (or similar) would be used.
  memcached:
    image: memcached:1.4.38-alpine
    command: memcached -m 128
    networks:
      - silex-network
    mem_limit: 128000000
    container_name: "memcached"

  # TODO : Remove. Likely Elasticache (or similar) would be used.
  redis:
    image: redis:3.2.9-alpine
    command: redis-server --appendonly yes
    volumes:
      - /var/lib/docker-persistant-data/redis-storage:/data
    networks:
      - silex-network
    mem_limit: 128000000
    container_name: "redis"

networks:
  silex-network:
    driver: bridge
