version: '2'

services:
  nginx:
    image: nginx:1.13.1-alpine
    ports:
      - "80:80"
    volumes:
      - ./app:/application
      - ./images/nginx/config/nginx.dev.conf:/etc/nginx/nginx.conf
      - ./images/nginx/config/web.conf:/etc/nginx/conf.d/default.conf
    networks:
      - silex-network
    mem_limit: 128000000
    container_name: "nginx"

  php:
    build:
      # Note: This is the same as server4001/php-fpm7.0-alpine:0.1.0, but I am leaving build here as a reference.
      context: ./images/php
      dockerfile: Dockerfile
    volumes:
      - ./images/php/config/php.dev.ini:/etc/php7/php.ini
      - ./images/php/config/pool.dev.conf:/etc/php7/php-fpm.d/www.conf
      - ./images/php/config/xdebug.ini:/etc/php7/conf.d/xdebug.ini
      - ./app:/application
    networks:
      - silex-network
    mem_limit: 256000000
    container_name: "php"

  db:
    image: sameersbn/mysql:latest
    volumes:
      - /var/lib/docker-persistant-data/mysql-storage:/var/lib/mysql
    environment:
      - DB_NAME=silex
      - DB_USER=silex_user
      - DB_PASS=silex_password
    networks:
      - silex-network
    mem_limit: 128000000
    container_name: "db"

  memcached:
    image: memcached:1.4.38-alpine
    command: memcached -m 128
    networks:
      - silex-network
    mem_limit: 128000000
    container_name: "memcached"

  redis:
    image: redis:3.2.9-alpine
    command: redis-server --appendonly yes
    volumes:
      - /var/lib/docker-persistant-data/redis-storage:/data
    networks:
      - silex-network
    mem_limit: 128000000
    container_name: "redis"

networks:
  silex-network:
    driver: bridge
