version: '2'

services:

  php:
    # docker build -f ./images/php/prod.Dockerfile -t server4001/silex-prod:0.1.0 .
    image: server4001/silex-prod:0.1.0
    working_dir: /application
    env_file: '.env.prod'
    networks:
      - silex-network
    mem_limit: 256000000
    container_name: "php"

  memcached:
    image: memcached:1.4.38-alpine
    command: memcached -m 128
    networks:
      - silex-network
    mem_limit: 128000000
    container_name: "memcached"

  redis:
    image: redis:3.2.9-alpine
    command: redis-server --appendonly yes
    volumes:
      - /var/lib/docker-persistant-data/redis-storage:/data
    networks:
      - silex-network
    mem_limit: 128000000
    container_name: "redis"

networks:
  silex-network:
    driver: bridge
