version: '2'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    networks:
      - nodeapp-network
  mongodb:
    image: mongo
    networks:
      - nodeapp-network

networks:
  nodeapp-network:
    driver: bridge
